#!/usr/bin/env node
/**
 * The brand mark: Switzerland's outline as nested contour lines converging on a red dot
 * (docs/DESIGN.md). Built from the geo spine so the shape is the real border: cantons merged,
 * simplified, smoothed, then scaled towards a focus point for the inner rings (similar copies
 * never cross). Writes the path data for React and a standalone SVG for the favicon.
 * Usage: node scripts/build-mark.mjs [--topo apps/web/public/geo/ch-2026.topo.json]
 */
import { readFileSync, writeFileSync, mkdirSync } from "node:fs";
import { dirname, join, resolve } from "node:path";
import { fileURLToPath } from "node:url";
import * as topojson from "topojson-client";

const here = dirname(fileURLToPath(import.meta.url));
const root = resolve(here, "..", "..", "..");
const arg = (name, fallback) => {
  const i = process.argv.indexOf(`--${name}`);
  return i >= 0 && process.argv[i + 1] ? process.argv[i + 1] : fallback;
};
const topoPath = resolve(root, arg("topo", "apps/web/public/geo/ch-2026.topo.json"));
const topo = JSON.parse(readFileSync(topoPath, "utf8"));
const merged = topojson.merge(topo, topo.objects.cantons.geometries);
// the mainland: the polygon with the largest ring
const rings = merged.type === "Polygon" ? [merged.coordinates[0]] : merged.coordinates.map((p) => p[0]);
const outline = rings.sort((a, b) => b.length - a.length)[0];

// equirectangular projection with latitude correction, fitted into a 1000 × 1000 box
const lat0 = 46.8;
const proj = ([lon, lat]) => [lon * Math.cos((lat0 * Math.PI) / 180), -lat];
let pts = outline.map(proj);
const xs = pts.map((p) => p[0]);
const ys = pts.map((p) => p[1]);
const minX = Math.min(...xs), maxX = Math.max(...xs), minY = Math.min(...ys), maxY = Math.max(...ys);
const span = Math.max(maxX - minX, maxY - minY);
const W = 1000, pad = 90;
const scale = (W - 2 * pad) / span;
const fit = ([x, y]) => [pad + (x - minX) * scale + ((W - 2 * pad) - (maxX - minX) * scale) / 2, pad + (y - minY) * scale + ((W - 2 * pad) - (maxY - minY) * scale) / 2];
pts = pts.map(fit);

// Douglas–Peucker simplification so the rings read as drawn lines, then Chaikin smoothing
function simplify(points, tol) {
  const sq = tol * tol;
  const keep = new Array(points.length).fill(false);
  keep[0] = keep[points.length - 1] = true;
  const stack = [[0, points.length - 1]];
  while (stack.length) {
    const [a, b] = stack.pop();
    let maxD = 0, idx = -1;
    const [ax, ay] = points[a], [bx, by] = points[b];
    const dx = bx - ax, dy = by - ay, len = dx * dx + dy * dy || 1;
    for (let i = a + 1; i < b; i++) {
      const [px, py] = points[i];
      const t = Math.max(0, Math.min(1, ((px - ax) * dx + (py - ay) * dy) / len));
      const ex = ax + t * dx - px, ey = ay + t * dy - py;
      const d = ex * ex + ey * ey;
      if (d > maxD) (maxD = d), (idx = i);
    }
    if (maxD > sq && idx > 0) (keep[idx] = true), stack.push([a, idx], [idx, b]);
  }
  return points.filter((_, i) => keep[i]);
}
function chaikin(points, iterations) {
  let p = points;
  for (let k = 0; k < iterations; k++) {
    const out = [];
    for (let i = 0; i < p.length; i++) {
      const a = p[i], b = p[(i + 1) % p.length];
      out.push([0.75 * a[0] + 0.25 * b[0], 0.75 * a[1] + 0.25 * b[1]]);
      out.push([0.25 * a[0] + 0.75 * b[0], 0.25 * a[1] + 0.75 * b[1]]);
    }
    p = out;
  }
  return p;
}
const base = chaikin(simplify(pts, 9), 2);

// focus: the visual centre of the country (near Sarnen) — the red dot, and the point the rings shrink towards
const focus = fit(proj([8.25, 46.85]));
const RINGS = 6;
const steps = Array.from({ length: RINGS }, (_, k) => 1 - k * 0.155);
const toPath = (points) =>
  `M${points.map(([x, y]) => `${x.toFixed(1)} ${y.toFixed(1)}`).join("L")}Z`;
const paths = steps.map((s) => toPath(base.map(([x, y]) => [focus[0] + (x - focus[0]) * s, focus[1] + (y - focus[1]) * s])));
const dot = [Number(focus[0].toFixed(1)), Number(focus[1].toFixed(1))];

const tsOut = resolve(root, "apps/web/lib/brand/mark.ts");
mkdirSync(dirname(tsOut), { recursive: true });
writeFileSync(
  tsOut,
  `// Generated by packages/geo-build/scripts/build-mark.mjs from the geo spine — do not edit.\nexport const MARK_VIEWBOX = "0 0 ${W} ${W}";\nexport const MARK_DOT: [number, number] = [${dot[0]}, ${dot[1]}];\nexport const MARK_DOT_R = 24;\nexport const MARK_STROKE = 9;\nexport const MARK_PATHS: string[] = ${JSON.stringify(paths, null, 2)};\n`,
);
const svg = (stroke, red, bg) =>
  `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 ${W} ${W}">${bg ? `<rect width="${W}" height="${W}" rx="180" fill="${bg}"/>` : ""}<g fill="none" stroke="${stroke}" stroke-width="9" stroke-linejoin="round" stroke-linecap="round">${paths.map((d) => `<path d="${d}"/>`).join("")}</g><circle cx="${dot[0]}" cy="${dot[1]}" r="24" fill="${red}"/></svg>\n`;
mkdirSync(resolve(root, "apps/web/public/brand"), { recursive: true });
writeFileSync(resolve(root, "apps/web/public/brand/mark.svg"), svg("#111827", "#E2563D", null));
writeFileSync(resolve(root, "apps/web/app/icon.svg"), svg("#111827", "#E2563D", "#FAFAF8"));
console.log(`mark: ${base.length} points per ring, ${RINGS} rings → apps/web/lib/brand/mark.ts, public/brand/mark.svg, app/icon.svg`);
