import type { LucideIcon } from "lucide-react";
import {
  ArrowLeftRight,
  CloudSun,
  Landmark,
  MapPin,
  Mountain,
  Plane,
  Snowflake,
  Thermometer,
  TrainFront,
  TrendingUp,
  TriangleAlert,
  Users,
  Waves,
  Wind,
  Zap,
  House,
  Vote,
  Droplets,
  Gauge,
  Activity,
  Timer,
  Building2,
  Percent,
  Sun,
  Flame,
} from "lucide-react";
import type { TopicId } from "@swiss-now/core/topics";

/** One outline icon per topic, in the drawn style of the brand sheet (Lucide, ISC). */
export const TOPIC_ICON: Record<TopicId, LucideIcon | null> = {
  now: null, // the live dot is drawn in CSS
  weather: CloudSun,
  water: Waves,
  air: Wind,
  hazards: TriangleAlert,
  events: MapPin,
  rail: TrainFront,
  energy: Zap,
  aviation: Plane,
  politics: Landmark,
  population: Users,
  housing: House,
  economy: TrendingUp,
  tourism: Mountain,
  trade: ArrowLeftRight,
};

/** Icons for the key figures by figure id; unknown ids fall back to the topic icon. */
export const FIGURE_ICON: Record<string, LucideIcon> = {
  warmest: Thermometer,
  coldest: Snowflake,
  gust: Wind,
  "rain-share": Droplets,
  snow: Snowflake,
  "rhine-basel": Waves,
  "warmest-river": Thermometer,
  "flood-danger": TriangleAlert,
  "on-time": Timer,
  "largest-delay": Timer,
  running: TrainFront,
  cancelled: TrainFront,
  disruptions: TriangleAlert,
  "net-flow": Zap,
  frequency: Gauge,
  price: TrendingUp,
  renewable: Sun,
  "last-quake": Activity,
  strongest: Activity,
  "quake-count": Activity,
  fire: Flame,
  avalanche: Mountain,
  hail: Snowflake,
  "air-index": Wind,
  pm25: Wind,
  citizen: Users,
  pollen: Sun,
  events: MapPin,
  "events-6h": MapPin,
  placed: MapPin,
  "top-canton": MapPin,
  yes: Vote,
  turnout: Percent,
  cantons: Landmark,
  "next-vote": Vote,
  top: TrendingUp,
  low: TrendingUp,
  national: Building2,
  count: Users,
  rank: TrendingUp,
  value: Building2,
  change: TrendingUp,
};
