import type { LocalizedText } from "../state/common";
import type { TopicGroup, TopicId, TopicSpec } from "./spec";

const MIN = 60;
const HOUR = 3600;
const DAY = 86_400;
const t = (de: string, en: string, fr?: string, it?: string): LocalizedText =>
  fr && it ? { de, en, fr, it } : { de, en };

export const TOPIC_GROUPS: { id: TopicGroup; label: LocalizedText }[] = [
  { id: "now", label: t("Jetzt", "Now", "Maintenant", "Adesso") },
  { id: "live", label: t("Live", "Live", "Live", "Live") },
  { id: "systems", label: t("Systeme", "Systems", "Systèmes", "Sistemi") },
  { id: "switzerland", label: t("Schweiz", "Switzerland", "Suisse", "Svizzera") },
];

/**
 * Declaration order = rail order within a group. `modes` lists what is implemented today and
 * grows stage by stage (docs/IA.md); the switcher dims the rest.
 */
export const TOPICS: Record<TopicId, TopicSpec> = {
  now: {
    id: "now",
    group: "now",
    label: t("Jetzt", "Now", "Maintenant", "Adesso"),
    accent: "weather",
    layerIds: ["weather", "hydrology", "rail", "seismic"],
    sources: ["meteoswiss-smn", "geoadmin-messwerte"],
    cadenceSeconds: 10 * MIN,
    geoLevel: "point",
    modes: ["map"],
    freshnessKind: "clock",
    built: true,
  },
  weather: {
    id: "weather",
    group: "live",
    label: t("Wetter", "Weather", "Météo", "Meteo"),
    accent: "weather",
    layerIds: ["weather"],
    sources: ["meteoswiss-smn", "meteoswiss-radar", "geoadmin-messwerte"],
    cadenceSeconds: 10 * MIN,
    geoLevel: "point",
    modes: ["map", "timeline"],
    freshnessKind: "clock",
    now: "always",
    built: true,
  },
  water: {
    id: "water",
    group: "live",
    label: t("Wasser", "Water", "Eau", "Acqua"),
    accent: "hydrology",
    layerIds: ["hydrology"],
    sources: ["bafu-lindas-hydro", "geoadmin-hydroweb"],
    cadenceSeconds: 10 * MIN,
    geoLevel: "point",
    modes: ["map"],
    freshnessKind: "clock",
    now: "notable",
    built: true,
  },
  air: {
    id: "air",
    group: "live",
    label: t("Luft", "Air", "Air", "Aria"),
    accent: "air",
    layerIds: ["air"],
    sources: ["ugz-air", "bs-air", "sensor-community", "meteoswiss-pollen"],
    cadenceSeconds: HOUR,
    geoLevel: "point",
    modes: ["map", "charts", "timeline", "compare"],
    freshnessKind: "clock",
    now: "notable",
    built: false,
  },
  hazards: {
    id: "hazards",
    group: "live",
    label: t("Gefahren", "Hazards", "Dangers", "Pericoli"),
    accent: "hazards",
    layerIds: ["seismic", "hazards"],
    sources: ["sed-fdsn", "slf-bulletin", "slf-imis", "bafu-fire-danger", "meteoswiss-hail"],
    cadenceSeconds: 2 * MIN,
    geoLevel: "point",
    modes: ["map"],
    freshnessKind: "clock",
    now: "notable",
    built: true,
  },
  events: {
    id: "events",
    group: "live",
    label: t("Ereignisse", "Events", "Événements", "Eventi"),
    accent: "events",
    layerIds: ["events"],
    sources: ["polizei-news", "srf-rss", "swisstopo", "bfs"],
    cadenceSeconds: 5 * MIN,
    geoLevel: "point",
    modes: ["map", "timeline", "charts"],
    freshnessKind: "clock",
    now: "notable",
    built: false,
  },
  rail: {
    id: "rail",
    group: "systems",
    label: t("Bahn", "Rail", "Rail", "Ferrovia"),
    accent: "rail",
    layerIds: ["rail"],
    sources: ["otd-gtfs-static", "otd-gtfs-rt", "sbb-rail-traffic-info", "sbb-line-geometry"],
    cadenceSeconds: MIN,
    geoLevel: "network",
    modes: ["map"],
    freshnessKind: "clock",
    now: "always",
    built: true,
  },
  energy: {
    id: "energy",
    group: "systems",
    label: t("Energie", "Energy", "Énergie", "Energia"),
    accent: "energy",
    layerIds: ["energy"],
    sources: ["swissgrid-live", "energy-charts", "sfoe-energy-dashboard"],
    cadenceSeconds: MIN,
    geoLevel: "country",
    modes: ["map", "charts", "timeline"],
    freshnessKind: "clock",
    now: "always",
    built: false,
  },
  aviation: {
    id: "aviation",
    group: "systems",
    label: t("Luftfahrt", "Aviation", "Aviation", "Aviazione"),
    accent: "aviation",
    layerIds: ["aviation"],
    sources: ["adsb-fi"],
    cadenceSeconds: 10,
    geoLevel: "point",
    modes: ["map", "timeline"],
    freshnessKind: "clock",
    built: false,
  },
  politics: {
    id: "politics",
    group: "switzerland",
    label: t("Politik", "Politics", "Politique", "Politica"),
    accent: "politics",
    layerIds: ["politics"],
    sources: ["bfs-pxweb", "swissvotes", "lindas-politics", "swisstopo"],
    cadenceSeconds: 7 * DAY,
    geoLevel: "municipality",
    modes: ["map", "timeline"],
    freshnessKind: "vintage",
    now: "vote-sunday",
    built: true,
  },
  population: {
    id: "population",
    group: "switzerland",
    label: t("Bevölkerung", "Population", "Population", "Popolazione"),
    accent: "population",
    layerIds: ["stats"],
    sources: ["bfs-sdmx", "bfs-pxweb", "swisstopo"],
    cadenceSeconds: 365 * DAY,
    geoLevel: "municipality",
    modes: ["map", "charts", "timeline", "compare"],
    freshnessKind: "vintage",
    built: false,
  },
  housing: {
    id: "housing",
    group: "switzerland",
    label: t("Wohnen", "Housing", "Logement", "Abitazioni"),
    accent: "housing",
    layerIds: ["stats"],
    sources: ["bfs-sdmx", "bfs-pxweb", "swisstopo"],
    cadenceSeconds: 365 * DAY,
    geoLevel: "municipality",
    modes: ["map", "charts", "timeline", "compare"],
    freshnessKind: "vintage",
    built: false,
  },
  economy: {
    id: "economy",
    group: "switzerland",
    label: t("Wirtschaft", "Economy", "Économie", "Economia"),
    accent: "economy",
    layerIds: ["stats"],
    sources: ["bfs-pxweb", "kof", "seco", "ecb", "swisstopo"],
    cadenceSeconds: 30 * DAY,
    geoLevel: "municipality",
    modes: ["map", "charts", "timeline", "compare"],
    freshnessKind: "vintage",
    built: false,
  },
  tourism: {
    id: "tourism",
    group: "switzerland",
    label: t("Tourismus", "Tourism", "Tourisme", "Turismo"),
    accent: "tourism",
    layerIds: ["stats"],
    sources: ["bfs-pxweb", "swisstopo"],
    cadenceSeconds: 30 * DAY,
    geoLevel: "canton",
    modes: ["map", "charts", "timeline", "compare"],
    freshnessKind: "vintage",
    built: false,
  },
  trade: {
    id: "trade",
    group: "switzerland",
    label: t("Handel", "Trade", "Commerce", "Commercio"),
    accent: "trade",
    layerIds: ["stats"],
    sources: ["eurostat"],
    cadenceSeconds: 30 * DAY,
    geoLevel: "world",
    modes: ["charts", "timeline"],
    freshnessKind: "vintage",
    built: false,
  },
};

export const TOPIC_ORDER: TopicId[] = Object.keys(TOPICS) as TopicId[];

export function getTopic(id: TopicId): TopicSpec {
  return TOPICS[id];
}

/** Topics of a group in rail order. */
export function topicsInGroup(group: TopicGroup): TopicSpec[] {
  return TOPIC_ORDER.map((id) => TOPICS[id]).filter((s) => s.group === group);
}
