/**
 * Source registry: licences, attribution strings and cadences as verified on 2026-09-07.
 * See docs/DATA_SOURCES.md for evidence and open questions. Keep this file boring and exact.
 */
import type { SourceMeta } from "./meta";
import type { SourceId } from "./ids";

const MIN = 60;
const HOUR = 3600;
const DAY = 86_400;

export const SOURCES: Record<SourceId, SourceMeta> = {
  "meteoswiss-smn": {
    id: "meteoswiss-smn",
    name: "SwissMetNet 10-minute station values",
    provider: "MeteoSwiss (Federal Office of Meteorology and Climatology)",
    attribution: "Source: MeteoSwiss",
    url: "https://opendatadocs.meteoswiss.ch/",
    license: "CC BY 4.0",
    commercialUse: "yes",
    cadenceSeconds: 10 * MIN,
    typicalLagSeconds: 9 * MIN,
    notes:
      "Files on data.geo.admin.ch (STAC). Windows-1252 CSV, UTC timestamps. Cadence may degrade to 60 min during incidents.",
  },
  "meteoswiss-radar": {
    id: "meteoswiss-radar",
    name: "Precipitation radar composites (RZC, CPC)",
    provider: "MeteoSwiss",
    attribution: "Source: MeteoSwiss",
    url: "https://opendatadocs.meteoswiss.ch/",
    license: "CC BY 4.0",
    commercialUse: "yes",
    cadenceSeconds: 5 * MIN,
    typicalLagSeconds: 2 * MIN,
    notes:
      "ODIM HDF5, EPSG:2056, rolling 14 days. Filenames are not deterministic — list STAC assets.",
  },
  "meteoswiss-forecast": {
    id: "meteoswiss-forecast",
    name: "Local forecast (app forecast, ~6 000 points)",
    provider: "MeteoSwiss",
    attribution: "Source: MeteoSwiss",
    url: "https://opendatadocs.meteoswiss.ch/",
    license: "CC BY 4.0 (weather pictograms excluded)",
    commercialUse: "yes",
    cadenceSeconds: HOUR,
    typicalLagSeconds: 0,
    notes: "Latin-1 CSV per parameter; hourly files up to 33 MB — process in GitHub Actions only.",
  },
  "geoadmin-messwerte": {
    id: "geoadmin-messwerte",
    name: "Pre-rendered MeteoSwiss measurement layers (GeoJSON)",
    provider: "MeteoSwiss via geo.admin.ch",
    attribution: "Source: MeteoSwiss · © swisstopo",
    url: "https://api3.geo.admin.ch/rest/services/all/MapServer/layersConfig",
    license: "opendata.swiss terms_open",
    commercialUse: "yes",
    cadenceSeconds: 5 * MIN,
    typicalLagSeconds: 6 * MIN,
    notes:
      "Coordinates are EPSG:2056 inside a GeoJSON envelope; reproject. Not a documented API contract — keep OGD CSVs as fallback.",
  },
  "geoadmin-hydroweb": {
    id: "geoadmin-hydroweb",
    name: "BAFU hydro class layers (danger levels, flood warning map)",
    provider: "FOEN/BAFU via geo.admin.ch",
    attribution: "Source: FOEN · © swisstopo",
    url: "https://api3.geo.admin.ch/rest/services/all/MapServer/layersConfig",
    license: "opendata.swiss terms_open",
    commercialUse: "yes",
    cadenceSeconds: 5 * MIN,
    typicalLagSeconds: 6 * MIN,
    notes: "Classes and symbols only, no numeric values. Use LINDAS for values.",
  },
  "bafu-lindas-hydro": {
    id: "bafu-lindas-hydro",
    name: "Hydrological current values (LINDAS SPARQL)",
    provider: "FOEN/BAFU",
    attribution: "Source: Federal Office for the Environment FOEN",
    url: "https://www.hydrodaten.admin.ch/en/aktuelle-hydrologische-daten-beziehen",
    license: "LINDAS Terms of Use: Open use (commercial allowed, reference not required)",
    commercialUse: "yes",
    cadenceSeconds: 10 * MIN,
    typicalLagSeconds: 21 * MIN,
    notes:
      "POST https://ld.admin.ch/query, graph <https://lindas.admin.ch/foen/hydro>. Dataset status Draft; measurementTime carries a fixed +01:00 offset.",
  },
  "sed-fdsn": {
    id: "sed-fdsn",
    name: "Swiss earthquake catalogue (FDSN event service)",
    provider: "Swiss Seismological Service (SED) at ETH Zurich",
    attribution: "Source: Swiss Seismological Service (SED) at ETH Zurich",
    url: "https://eida.ethz.ch/fdsnws/event/1/",
    license:
      "Unresolved — SED disclaimer permits private, scientific and non-commercial use; written clarification requested",
    commercialUse: "unresolved",
    cadenceSeconds: 2 * MIN,
    typicalLagSeconds: 10 * HOUR,
    notes:
      "Manually reviewed catalogue; reviewed origins appear hours after the event. No JSON output — use text or QuakeML.",
  },
  "otd-gtfs-static": {
    id: "otd-gtfs-static",
    name: "GTFS static timetable (FP2026)",
    provider: "Open Data Platform Mobility Switzerland (opentransportdata.swiss)",
    attribution: "Source: opentransportdata.swiss",
    url: "https://opentransportdata.swiss/en/cookbook/timetable-cookbook/gtfs/",
    license: "opentransportdata.swiss terms of use (commercial allowed, cite source)",
    commercialUse: "yes",
    cadenceSeconds: 3 * DAY,
    typicalLagSeconds: 0,
    notes:
      "Published Mon + Thu; ~237 MiB; no shapes.txt. Resource UUIDs change per release — discover via CKAN package_show.",
  },
  "otd-gtfs-rt": {
    id: "otd-gtfs-rt",
    name: "GTFS-RT TripUpdates and Service Alerts",
    provider: "Open Data Platform Mobility Switzerland",
    attribution: "Source: opentransportdata.swiss",
    url: "https://opentransportdata.swiss/en/cookbook/realtime-prediction-cookbook/gtfs-rt/",
    license: "opentransportdata.swiss terms of use",
    commercialUse: "yes",
    cadenceSeconds: MIN,
    typicalLagSeconds: 30,
    notes:
      "Rate limit documented as 2/min (cookbook) and 5/min (limits page) — poll at most once per minute. No vehicle positions are published; all positions are interpolated.",
  },
  "otd-siri-sx": {
    id: "otd-siri-sx",
    name: "SIRI-SX situation exchange (disruptions)",
    provider: "Open Data Platform Mobility Switzerland",
    attribution: "Source: opentransportdata.swiss",
    url: "https://opentransportdata.swiss/en/cookbook/event-cookbook/siri-sx/",
    license: "opentransportdata.swiss terms of use",
    commercialUse: "yes",
    cadenceSeconds: 2 * MIN,
    typicalLagSeconds: 30,
    notes: "2 req/min, 3 000 req/day.",
  },
  "sbb-line-geometry": {
    id: "sbb-line-geometry",
    name: "SBB Line (graphical) — route geometry",
    provider: "SBB Infrastructure (data.sbb.ch)",
    attribution: "Source: SBB",
    url: "https://data.sbb.ch/explore/dataset/linie-mit-polygon/",
    license: "Terms by (NonCommercialAllowed-CommercialAllowed-ReferenceRequired)",
    commercialUse: "yes",
    cadenceSeconds: 7 * DAY,
    typicalLagSeconds: 0,
    notes: "3 147 LineStrings, weekly. SBB infrastructure lines; private railways via BAV network.",
  },
  "sbb-rail-traffic-info": {
    id: "sbb-rail-traffic-info",
    name: "SBB rail traffic information (disruption messages)",
    provider: "SBB Passenger Traffic (data.sbb.ch)",
    attribution: "Source: SBB",
    url: "https://data.sbb.ch/explore/dataset/rail-traffic-information/",
    license: "Terms by (NonCommercialAllowed-CommercialAllowed-ReferenceRequired)",
    commercialUse: "yes",
    cadenceSeconds: 5 * MIN,
    typicalLagSeconds: 0,
    notes: "Text messages only, no geometry.",
  },
  "bav-rail-network": {
    id: "bav-rail-network",
    name: "Swiss railway network (Schienennetz)",
    provider: "Federal Office of Transport (BAV/FOT) via geo.admin.ch",
    attribution: "Source: FOT · © swisstopo",
    url: "https://data.geo.admin.ch/api/stac/v1/collections/ch.bav.schienennetz",
    license: "opendata.swiss terms_by",
    commercialUse: "yes",
    cadenceSeconds: 365 * DAY,
    typicalLagSeconds: 0,
    notes: "FileGDB / INTERLIS in LV95 only; converted at build time.",
  },
  "fedro-datex2": {
    id: "fedro-datex2",
    name: "Road traffic situations and counters (DATEX II)",
    provider: "Federal Roads Office (FEDRO/ASTRA) Traffic Data Platform",
    attribution: "Data source: Federal Roads Office (FEDRO) Traffic Data Platform (TDP).",
    url: "https://opentransportdata.swiss/en/road-traffic/",
    license:
      "FEDRO terms: attribution required; raw machine-readable redistribution prohibited; 260 000-call quota on standard access",
    commercialUse: "ask",
    cadenceSeconds: 5 * MIN,
    typicalLagSeconds: 20,
    notes:
      "Phase 5. Public API may expose derived values only. SOAP, DATEX II 2.2.3 (situations) and 2.3 (counters), TMC location codes.",
  },
  "slf-imis": {
    id: "slf-imis",
    name: "IMIS snow and wind stations",
    provider: "WSL Institute for Snow and Avalanche Research SLF",
    attribution: "Source: WSL Institute for Snow and Avalanche Research SLF",
    url: "https://measurement-api.slf.ch/",
    license: "CC BY 4.0",
    commercialUse: "yes",
    cadenceSeconds: 30 * MIN,
    typicalLagSeconds: 15 * MIN,
  },
  "slf-bulletin": {
    id: "slf-bulletin",
    name: "Avalanche bulletin (CAAML / GeoJSON)",
    provider: "WSL Institute for Snow and Avalanche Research SLF",
    attribution: "Source: WSL Institute for Snow and Avalanche Research SLF",
    url: "https://aws.slf.ch/api/bulletin/caaml",
    license: "CC BY 4.0",
    commercialUse: "yes",
    cadenceSeconds: 12 * HOUR,
    typicalLagSeconds: 0,
    notes: "Twice daily in winter; empty in summer.",
  },
  "bafu-fire-danger": {
    id: "bafu-fire-danger",
    name: "Forest fire danger warning",
    provider: "FOEN/BAFU via geo.admin.ch",
    attribution: "Source: FOEN · © swisstopo",
    url: "https://data.geo.admin.ch/api/stac/v0.9/collections/ch.bafu.gefahren-waldbrand_warnung",
    license: "opendata.swiss terms_open",
    commercialUse: "yes",
    cadenceSeconds: DAY,
    typicalLagSeconds: 0,
  },
  entsoe: {
    id: "entsoe",
    name: "ENTSO-E Transparency Platform (CH load, generation, flows)",
    provider: "ENTSO-E / Swissgrid",
    attribution: "Source: ENTSO-E Transparency Platform",
    url: "https://transparency.entsoe.eu/",
    license: "To confirm (reuse terms not verified)",
    commercialUse: "unresolved",
    cadenceSeconds: 15 * MIN,
    typicalLagSeconds: HOUR,
    notes: "Phase 5. Free token by email; 400 req/min.",
  },
  "sfoe-energy-dashboard": {
    id: "sfoe-energy-dashboard",
    name: "Energy Dashboard Switzerland daily series",
    provider: "Swiss Federal Office of Energy (SFOE/BFE)",
    attribution: "Source: SFOE / Swissgrid",
    url: "https://www.bfe-ogd.ch/",
    license:
      "Mixed: terms_by (import/export, estimated consumption) and terms_by_ask (production mix, consumption, spot price)",
    commercialUse: "ask",
    cadenceSeconds: DAY,
    typicalLagSeconds: DAY,
    notes: "Production CSV contains ~12 forecast days (empty Speicherkraft). Story use only.",
  },
  sharedmobility: {
    id: "sharedmobility",
    name: "sharedmobility.ch GBFS (bikes, e-scooters, car sharing)",
    provider: "Swiss Federal Office of Energy (SFOE)",
    attribution: "Source: sharedmobility.ch (SFOE)",
    url: "https://github.com/SFOE/sharedmobility",
    license: "Commercial and non-commercial reuse permitted with attribution",
    commercialUse: "yes",
    cadenceSeconds: MIN,
    typicalLagSeconds: 0,
    notes: "Phase 5 optional. True reported positions.",
  },
  swisstopo: {
    id: "swisstopo",
    name: "swisstopo vector tiles, WMTS, boundaries",
    provider: "Federal Office of Topography swisstopo",
    attribution: "© swisstopo",
    url: "https://www.swisstopo.admin.ch/en/terms-of-use-free-geodata-and-geoservices",
    license:
      "Free geodata and geoservices (commercial allowed, attribution required, fair use ≈ 20 000 users/day)",
    commercialUse: "yes",
    cadenceSeconds: DAY,
    typicalLagSeconds: 0,
    notes:
      "Use ch.swisstopo.lightbasemap.vt; leichte-basiskarte.vt was broken on 2026-09-07. No terrain-RGB tiles exist.",
  },
  bfs: {
    id: "bfs",
    name: "Federal Statistical Office (population, municipalities, typologies)",
    provider: "Federal Statistical Office (BFS/FSO)",
    attribution: "Source: FSO",
    url: "https://www.bfs.admin.ch/",
    license: "OPEN BY",
    commercialUse: "yes",
    cadenceSeconds: 365 * DAY,
    typicalLagSeconds: 0,
    notes:
      "PxWeb is migrating to Swiss Stats Explorer (SDMX). agvchapp municipality register for typologies.",
  },
};

export function getSource(id: SourceId): SourceMeta {
  return SOURCES[id];
}

export function listSources(): SourceMeta[] {
  return Object.values(SOURCES);
}
